- name: check old folder name existing
  stat: path=/home/{{ ansible_user }}/{{ oldName }}
  register: statStatus

- name: ensure old folder is renamed to new folder
  command: mv /home/{{ ansible_user }}/{{ oldName }} /home/{{ ansible_user }}/{{ newName }}
  when: statStatus.stat.exists and oldName is defined

- name: create new folder if there is no defined old folder
  command: mkdir /home/{{ ansible_user }}/{{ newName }}
  when: newName is defined and oldName is undefined

- lineinfile:
    path: /home/{{ ansible_user }}/.config/user-dirs.dirs
    regexp: '^XDG_DESKTOP_DIR='
    line: XDG_DESKTOP_DIR="$HOME/{{ newName }}"
  when: statStatus.stat.exists and oldName is defined
