- name: check old folder name existing
  stat: path=/home/{{ ansible_user }}/{{ item.oldName }}
  register: statStatus

- name: ensure old folder is renamed to new folder
  command: mv /home/{{ ansible_user }}/{{ item.oldName }} /home/{{ ansible_user }}/{{ item.newName }}
  when: statStatus.stat.exists and item.oldName is defined

- name: ensure config is set for {{ item.newName }}
  lineinfile:
    path: /home/{{ ansible_user }}/.config/user-dirs.dirs
    regexp: ^{{ item.variableName }}=
    line: "{{ item.variableName }}=$HOME/{{ item.newName }}"
  when: statStatus.stat.exists and item.oldName is defined
