- name: check old folder name existing
  stat: path=/home/{{ ansible_user }}/{{ item.oldName }}
  register: statStatus

- name: ensure old folder is renamed to new folder
  command: mv /home/{{ ansible_user }}/{{ item.oldName }} /home/{{ ansible_user }}/{{ item.newName }}
  when: statStatus.stat.exists and item.oldName is defined

- lineinfile:
    path: /home/{{ ansible_user }}/.config/user-dirs.dirs
    regexp: '^XDG_DESKTOP_DIR='
    line: XDG_DESKTOP_DIR="$HOME/{{ item.newName }}"
  when: statStatus.stat.exists and item.oldName is defined
